// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc-helloworld.proto

package com.hservice.grpc.schema;

public interface HelloReplyUpdateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HelloReplyUpdate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string message = 1;</code>
   */
  String getMessage();
  /**
   * <code>optional string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>optional .HelloReplyObject helloReplyObject = 2;</code>
   */
  boolean hasHelloReplyObject();
  /**
   * <code>optional .HelloReplyObject helloReplyObject = 2;</code>
   */
  HelloReplyObject getHelloReplyObject();
  /**
   * <code>optional .HelloReplyObject helloReplyObject = 2;</code>
   */
  HelloReplyObjectOrBuilder getHelloReplyObjectOrBuilder();
}
