// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc-helloworld.proto

package com.hservice.grpc.schema;

/**
 * <pre>
 * The greeting service definition.
 * </pre>
 *
 * Protobuf service {@code Greeter}
 */
public  abstract class Greeter
    implements com.google.protobuf.Service {
  protected Greeter() {}

  public interface Interface {
    /**
     * <pre>
     * Sends a greeting
     * </pre>
     *
     * <code>rpc SayHello(.HelloRequest) returns (.HelloReply);</code>
     */
    public abstract void sayHello(
            com.google.protobuf.RpcController controller,
            HelloRequest request,
            com.google.protobuf.RpcCallback<HelloReply> done);

    /**
     * <code>rpc SayHelloAgain(.HelloRequest) returns (.HelloReply);</code>
     */
    public abstract void sayHelloAgain(
            com.google.protobuf.RpcController controller,
            HelloRequest request,
            com.google.protobuf.RpcCallback<HelloReply> done);

    /**
     * <code>rpc getData(.HelloRequest) returns (.HelloReplyUpdate);</code>
     */
    public abstract void getData(
            com.google.protobuf.RpcController controller,
            HelloRequest request,
            com.google.protobuf.RpcCallback<HelloReplyUpdate> done);

  }

  public static com.google.protobuf.Service newReflectiveService(
      final Interface impl) {
    return new Greeter() {
      @Override
      public  void sayHello(
          com.google.protobuf.RpcController controller,
          HelloRequest request,
          com.google.protobuf.RpcCallback<HelloReply> done) {
        impl.sayHello(controller, request, done);
      }

      @Override
      public  void sayHelloAgain(
          com.google.protobuf.RpcController controller,
          HelloRequest request,
          com.google.protobuf.RpcCallback<HelloReply> done) {
        impl.sayHelloAgain(controller, request, done);
      }

      @Override
      public  void getData(
          com.google.protobuf.RpcController controller,
          HelloRequest request,
          com.google.protobuf.RpcCallback<HelloReplyUpdate> done) {
        impl.getData(controller, request, done);
      }

    };
  }

  public static com.google.protobuf.BlockingService
      newReflectiveBlockingService(final BlockingInterface impl) {
    return new com.google.protobuf.BlockingService() {
      public final com.google.protobuf.Descriptors.ServiceDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }

      public final com.google.protobuf.Message callBlockingMethod(
          com.google.protobuf.Descriptors.MethodDescriptor method,
          com.google.protobuf.RpcController controller,
          com.google.protobuf.Message request)
          throws com.google.protobuf.ServiceException {
        if (method.getService() != getDescriptor()) {
          throw new IllegalArgumentException(
            "Service.callBlockingMethod() given method descriptor for " +
            "wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return impl.sayHello(controller, (HelloRequest)request);
          case 1:
            return impl.sayHelloAgain(controller, (HelloRequest)request);
          case 2:
            return impl.getData(controller, (HelloRequest)request);
          default:
            throw new AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getRequestPrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new IllegalArgumentException(
            "Service.getRequestPrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return HelloRequest.getDefaultInstance();
          case 1:
            return HelloRequest.getDefaultInstance();
          case 2:
            return HelloRequest.getDefaultInstance();
          default:
            throw new AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getResponsePrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new IllegalArgumentException(
            "Service.getResponsePrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return HelloReply.getDefaultInstance();
          case 1:
            return HelloReply.getDefaultInstance();
          case 2:
            return HelloReplyUpdate.getDefaultInstance();
          default:
            throw new AssertionError("Can't get here.");
        }
      }

    };
  }

  /**
   * <pre>
   * Sends a greeting
   * </pre>
   *
   * <code>rpc SayHello(.HelloRequest) returns (.HelloReply);</code>
   */
  public abstract void sayHello(
      com.google.protobuf.RpcController controller,
      HelloRequest request,
      com.google.protobuf.RpcCallback<HelloReply> done);

  /**
   * <code>rpc SayHelloAgain(.HelloRequest) returns (.HelloReply);</code>
   */
  public abstract void sayHelloAgain(
      com.google.protobuf.RpcController controller,
      HelloRequest request,
      com.google.protobuf.RpcCallback<HelloReply> done);

  /**
   * <code>rpc getData(.HelloRequest) returns (.HelloReplyUpdate);</code>
   */
  public abstract void getData(
      com.google.protobuf.RpcController controller,
      HelloRequest request,
      com.google.protobuf.RpcCallback<HelloReplyUpdate> done);

  public static final
      com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptor() {
    return HelloWorldProto.getDescriptor().getServices().get(0);
  }
  public final com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }

  public final void callMethod(
      com.google.protobuf.Descriptors.MethodDescriptor method,
      com.google.protobuf.RpcController controller,
      com.google.protobuf.Message request,
      com.google.protobuf.RpcCallback<
        com.google.protobuf.Message> done) {
    if (method.getService() != getDescriptor()) {
      throw new IllegalArgumentException(
        "Service.callMethod() given method descriptor for wrong " +
        "service type.");
    }
    switch(method.getIndex()) {
      case 0:
        this.sayHello(controller, (HelloRequest)request,
          com.google.protobuf.RpcUtil.<HelloReply>specializeCallback(
            done));
        return;
      case 1:
        this.sayHelloAgain(controller, (HelloRequest)request,
          com.google.protobuf.RpcUtil.<HelloReply>specializeCallback(
            done));
        return;
      case 2:
        this.getData(controller, (HelloRequest)request,
          com.google.protobuf.RpcUtil.<HelloReplyUpdate>specializeCallback(
            done));
        return;
      default:
        throw new AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getRequestPrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new IllegalArgumentException(
        "Service.getRequestPrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return HelloRequest.getDefaultInstance();
      case 1:
        return HelloRequest.getDefaultInstance();
      case 2:
        return HelloRequest.getDefaultInstance();
      default:
        throw new AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getResponsePrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new IllegalArgumentException(
        "Service.getResponsePrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return HelloReply.getDefaultInstance();
      case 1:
        return HelloReply.getDefaultInstance();
      case 2:
        return HelloReplyUpdate.getDefaultInstance();
      default:
        throw new AssertionError("Can't get here.");
    }
  }

  public static Stub newStub(
      com.google.protobuf.RpcChannel channel) {
    return new Stub(channel);
  }

  public static final class Stub extends Greeter implements Interface {
    private Stub(com.google.protobuf.RpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.RpcChannel channel;

    public com.google.protobuf.RpcChannel getChannel() {
      return channel;
    }

    public  void sayHello(
        com.google.protobuf.RpcController controller,
        HelloRequest request,
        com.google.protobuf.RpcCallback<HelloReply> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        HelloReply.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          HelloReply.class,
          HelloReply.getDefaultInstance()));
    }

    public  void sayHelloAgain(
        com.google.protobuf.RpcController controller,
        HelloRequest request,
        com.google.protobuf.RpcCallback<HelloReply> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(1),
        controller,
        request,
        HelloReply.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          HelloReply.class,
          HelloReply.getDefaultInstance()));
    }

    public  void getData(
        com.google.protobuf.RpcController controller,
        HelloRequest request,
        com.google.protobuf.RpcCallback<HelloReplyUpdate> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(2),
        controller,
        request,
        HelloReplyUpdate.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          HelloReplyUpdate.class,
          HelloReplyUpdate.getDefaultInstance()));
    }
  }

  public static BlockingInterface newBlockingStub(
      com.google.protobuf.BlockingRpcChannel channel) {
    return new BlockingStub(channel);
  }

  public interface BlockingInterface {
    public HelloReply sayHello(
            com.google.protobuf.RpcController controller,
            HelloRequest request)
        throws com.google.protobuf.ServiceException;

    public HelloReply sayHelloAgain(
            com.google.protobuf.RpcController controller,
            HelloRequest request)
        throws com.google.protobuf.ServiceException;

    public HelloReplyUpdate getData(
            com.google.protobuf.RpcController controller,
            HelloRequest request)
        throws com.google.protobuf.ServiceException;
  }

  private static final class BlockingStub implements BlockingInterface {
    private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.BlockingRpcChannel channel;

    public HelloReply sayHello(
        com.google.protobuf.RpcController controller,
        HelloRequest request)
        throws com.google.protobuf.ServiceException {
      return (HelloReply) channel.callBlockingMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        HelloReply.getDefaultInstance());
    }


    public HelloReply sayHelloAgain(
        com.google.protobuf.RpcController controller,
        HelloRequest request)
        throws com.google.protobuf.ServiceException {
      return (HelloReply) channel.callBlockingMethod(
        getDescriptor().getMethods().get(1),
        controller,
        request,
        HelloReply.getDefaultInstance());
    }


    public HelloReplyUpdate getData(
        com.google.protobuf.RpcController controller,
        HelloRequest request)
        throws com.google.protobuf.ServiceException {
      return (HelloReplyUpdate) channel.callBlockingMethod(
        getDescriptor().getMethods().get(2),
        controller,
        request,
        HelloReplyUpdate.getDefaultInstance());
    }

  }

  // @@protoc_insertion_point(class_scope:Greeter)
}

