// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc-helloworld.proto

package com.hservice.grpc.schema;

public final class HelloWorldProto {
  private HelloWorldProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HelloReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HelloReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HelloReplyObject_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HelloReplyObject_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HelloReplyUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HelloReplyUpdate_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\025grpc-helloworld.proto\"\034\n\014HelloRequest\022" +
      "\014\n\004name\030\001 \001(\t\"\035\n\nHelloReply\022\017\n\007message\030\001" +
      " \001(\t\",\n\020HelloReplyObject\022\n\n\002id\030\001 \001(\t\022\014\n\004" +
      "name\030\002 \001(\t\"P\n\020HelloReplyUpdate\022\017\n\007messag" +
      "e\030\001 \001(\t\022+\n\020helloReplyObject\030\002 \001(\0132\021.Hell" +
      "oReplyObject2\221\001\n\007Greeter\022(\n\010SayHello\022\r.H" +
      "elloRequest\032\013.HelloReply\"\000\022-\n\rSayHelloAg" +
      "ain\022\r.HelloRequest\032\013.HelloReply\"\000\022-\n\007get" +
      "Data\022\r.HelloRequest\032\021.HelloReplyUpdate\"\000" +
      "B0\n\030com.hservice.grpc.schemaB\017HelloWorld",
      "ProtoP\001\210\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HelloRequest_descriptor,
        new String[] { "Name", });
    internal_static_HelloReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_HelloReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HelloReply_descriptor,
        new String[] { "Message", });
    internal_static_HelloReplyObject_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_HelloReplyObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HelloReplyObject_descriptor,
        new String[] { "Id", "Name", });
    internal_static_HelloReplyUpdate_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_HelloReplyUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HelloReplyUpdate_descriptor,
        new String[] { "Message", "HelloReplyObject", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
