// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc-helloworld.proto

package com.hservice.grpc.schema;

public interface HelloReplyObjectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HelloReplyObject)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string id = 1;</code>
   */
  String getId();
  /**
   * <code>optional string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>optional string name = 2;</code>
   */
  String getName();
  /**
   * <code>optional string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
