// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc-helloworld.proto

package com.hservice.grpc.schema;

public interface HelloRequestIntOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HelloRequestInt)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 name = 1;</code>
   */
  int getName();
}
