// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc-helloworld.proto

package com.hservice.grpc.schema;

/**
 * <pre>
 * The response message containing the greetings
 * </pre>
 *
 * Protobuf type {@code HelloReplyUpdate}
 */
public  final class HelloReplyUpdate extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:HelloReplyUpdate)
    HelloReplyUpdateOrBuilder {
  // Use HelloReplyUpdate.newBuilder() to construct.
  private HelloReplyUpdate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HelloReplyUpdate() {
    message_ = "";
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private HelloReplyUpdate(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            String s = input.readStringRequireUtf8();

            message_ = s;
            break;
          }
          case 18: {
            HelloReplyObject.Builder subBuilder = null;
            if (helloReplyObject_ != null) {
              subBuilder = helloReplyObject_.toBuilder();
            }
            helloReplyObject_ = input.readMessage(HelloReplyObject.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(helloReplyObject_);
              helloReplyObject_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return HelloWorldProto.internal_static_HelloReplyUpdate_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return HelloWorldProto.internal_static_HelloReplyUpdate_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            HelloReplyUpdate.class, HelloReplyUpdate.Builder.class);
  }

  public static final int MESSAGE_FIELD_NUMBER = 1;
  private volatile Object message_;
  /**
   * <code>optional string message = 1;</code>
   */
  public String getMessage() {
    Object ref = message_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <code>optional string message = 1;</code>
   */
  public com.google.protobuf.ByteString
      getMessageBytes() {
    Object ref = message_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HELLOREPLYOBJECT_FIELD_NUMBER = 2;
  private HelloReplyObject helloReplyObject_;
  /**
   * <code>optional .HelloReplyObject helloReplyObject = 2;</code>
   */
  public boolean hasHelloReplyObject() {
    return helloReplyObject_ != null;
  }
  /**
   * <code>optional .HelloReplyObject helloReplyObject = 2;</code>
   */
  public HelloReplyObject getHelloReplyObject() {
    return helloReplyObject_ == null ? HelloReplyObject.getDefaultInstance() : helloReplyObject_;
  }
  /**
   * <code>optional .HelloReplyObject helloReplyObject = 2;</code>
   */
  public HelloReplyObjectOrBuilder getHelloReplyObjectOrBuilder() {
    return getHelloReplyObject();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, message_);
    }
    if (helloReplyObject_ != null) {
      output.writeMessage(2, getHelloReplyObject());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, message_);
    }
    if (helloReplyObject_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getHelloReplyObject());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof HelloReplyUpdate)) {
      return super.equals(obj);
    }
    HelloReplyUpdate other = (HelloReplyUpdate) obj;

    boolean result = true;
    result = result && getMessage()
        .equals(other.getMessage());
    result = result && (hasHelloReplyObject() == other.hasHelloReplyObject());
    if (hasHelloReplyObject()) {
      result = result && getHelloReplyObject()
          .equals(other.getHelloReplyObject());
    }
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    if (hasHelloReplyObject()) {
      hash = (37 * hash) + HELLOREPLYOBJECT_FIELD_NUMBER;
      hash = (53 * hash) + getHelloReplyObject().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static HelloReplyUpdate parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static HelloReplyUpdate parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static HelloReplyUpdate parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static HelloReplyUpdate parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static HelloReplyUpdate parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static HelloReplyUpdate parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static HelloReplyUpdate parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static HelloReplyUpdate parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static HelloReplyUpdate parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static HelloReplyUpdate parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(HelloReplyUpdate prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The response message containing the greetings
   * </pre>
   *
   * Protobuf type {@code HelloReplyUpdate}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:HelloReplyUpdate)
      HelloReplyUpdateOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return HelloWorldProto.internal_static_HelloReplyUpdate_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HelloWorldProto.internal_static_HelloReplyUpdate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              HelloReplyUpdate.class, HelloReplyUpdate.Builder.class);
    }

    // Construct using com.hservice.grpc.schema.HelloReplyUpdate.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      message_ = "";

      if (helloReplyObjectBuilder_ == null) {
        helloReplyObject_ = null;
      } else {
        helloReplyObject_ = null;
        helloReplyObjectBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return HelloWorldProto.internal_static_HelloReplyUpdate_descriptor;
    }

    public HelloReplyUpdate getDefaultInstanceForType() {
      return HelloReplyUpdate.getDefaultInstance();
    }

    public HelloReplyUpdate build() {
      HelloReplyUpdate result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public HelloReplyUpdate buildPartial() {
      HelloReplyUpdate result = new HelloReplyUpdate(this);
      result.message_ = message_;
      if (helloReplyObjectBuilder_ == null) {
        result.helloReplyObject_ = helloReplyObject_;
      } else {
        result.helloReplyObject_ = helloReplyObjectBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof HelloReplyUpdate) {
        return mergeFrom((HelloReplyUpdate)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(HelloReplyUpdate other) {
      if (other == HelloReplyUpdate.getDefaultInstance()) return this;
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        onChanged();
      }
      if (other.hasHelloReplyObject()) {
        mergeHelloReplyObject(other.getHelloReplyObject());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      HelloReplyUpdate parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (HelloReplyUpdate) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object message_ = "";
    /**
     * <code>optional string message = 1;</code>
     */
    public String getMessage() {
      Object ref = message_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string message = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string message = 1;</code>
     */
    public Builder setMessage(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      message_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string message = 1;</code>
     */
    public Builder clearMessage() {

      message_ = getDefaultInstance().getMessage();
      onChanged();
      return this;
    }
    /**
     * <code>optional string message = 1;</code>
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      message_ = value;
      onChanged();
      return this;
    }

    private HelloReplyObject helloReplyObject_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        HelloReplyObject, HelloReplyObject.Builder, HelloReplyObjectOrBuilder> helloReplyObjectBuilder_;
    /**
     * <code>optional .HelloReplyObject helloReplyObject = 2;</code>
     */
    public boolean hasHelloReplyObject() {
      return helloReplyObjectBuilder_ != null || helloReplyObject_ != null;
    }
    /**
     * <code>optional .HelloReplyObject helloReplyObject = 2;</code>
     */
    public HelloReplyObject getHelloReplyObject() {
      if (helloReplyObjectBuilder_ == null) {
        return helloReplyObject_ == null ? HelloReplyObject.getDefaultInstance() : helloReplyObject_;
      } else {
        return helloReplyObjectBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .HelloReplyObject helloReplyObject = 2;</code>
     */
    public Builder setHelloReplyObject(HelloReplyObject value) {
      if (helloReplyObjectBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        helloReplyObject_ = value;
        onChanged();
      } else {
        helloReplyObjectBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .HelloReplyObject helloReplyObject = 2;</code>
     */
    public Builder setHelloReplyObject(
        HelloReplyObject.Builder builderForValue) {
      if (helloReplyObjectBuilder_ == null) {
        helloReplyObject_ = builderForValue.build();
        onChanged();
      } else {
        helloReplyObjectBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .HelloReplyObject helloReplyObject = 2;</code>
     */
    public Builder mergeHelloReplyObject(HelloReplyObject value) {
      if (helloReplyObjectBuilder_ == null) {
        if (helloReplyObject_ != null) {
          helloReplyObject_ =
            HelloReplyObject.newBuilder(helloReplyObject_).mergeFrom(value).buildPartial();
        } else {
          helloReplyObject_ = value;
        }
        onChanged();
      } else {
        helloReplyObjectBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .HelloReplyObject helloReplyObject = 2;</code>
     */
    public Builder clearHelloReplyObject() {
      if (helloReplyObjectBuilder_ == null) {
        helloReplyObject_ = null;
        onChanged();
      } else {
        helloReplyObject_ = null;
        helloReplyObjectBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .HelloReplyObject helloReplyObject = 2;</code>
     */
    public HelloReplyObject.Builder getHelloReplyObjectBuilder() {

      onChanged();
      return getHelloReplyObjectFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .HelloReplyObject helloReplyObject = 2;</code>
     */
    public HelloReplyObjectOrBuilder getHelloReplyObjectOrBuilder() {
      if (helloReplyObjectBuilder_ != null) {
        return helloReplyObjectBuilder_.getMessageOrBuilder();
      } else {
        return helloReplyObject_ == null ?
            HelloReplyObject.getDefaultInstance() : helloReplyObject_;
      }
    }
    /**
     * <code>optional .HelloReplyObject helloReplyObject = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        HelloReplyObject, HelloReplyObject.Builder, HelloReplyObjectOrBuilder>
        getHelloReplyObjectFieldBuilder() {
      if (helloReplyObjectBuilder_ == null) {
        helloReplyObjectBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            HelloReplyObject, HelloReplyObject.Builder, HelloReplyObjectOrBuilder>(
                getHelloReplyObject(),
                getParentForChildren(),
                isClean());
        helloReplyObject_ = null;
      }
      return helloReplyObjectBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:HelloReplyUpdate)
  }

  // @@protoc_insertion_point(class_scope:HelloReplyUpdate)
  private static final HelloReplyUpdate DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new HelloReplyUpdate();
  }

  public static HelloReplyUpdate getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HelloReplyUpdate>
      PARSER = new com.google.protobuf.AbstractParser<HelloReplyUpdate>() {
    public HelloReplyUpdate parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new HelloReplyUpdate(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<HelloReplyUpdate> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<HelloReplyUpdate> getParserForType() {
    return PARSER;
  }

  public HelloReplyUpdate getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

